server:
  port: 80

spring:
  datasource:
    url: jdbc:sqlite:/app/data/sfia-sqlite.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: false  # Ensure quotes aren't added
        dialect:
          storage_engine: org.hibernate.community.dialect.SQLiteDialect
  data:
    rest:
      base-path: /
      return-body-on-create: true
      return-body-on-update: true
      default-page-size: 20